### PR TITLE
Docker setup

### PR DESCRIPTION
**Pull request by KaitCrawford**

### CODE REVIEW

**Comment by KaitCrawford** [comment]
@hodgestar added Dockerfile and entrypoint file that we can work from. The docker file is only slightly changed from smn's one

**Comment by hodgestar** [comment]
:+1:

**Comment by KaitCrawford** [comment]
@hodgestar isn't there more that should happen? I was intending this to be where we could work on and review  the setup of the docker file. Would you prefer I land this and have a new branch for each step so PRs are easier to review?

**Comment by hodgestar** [comment]
I saw this as just bring across @smn's original Dockerfile and that we'd
modify it in further PRs.

**Pull request merged**
