### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by JayH5**
Going commit-by-commit is probably best, but basically:
- Move requirements to requirements file so we can use requires.io
- Clean up scripts, add more quoting
- Ditch supervisor
- Use a new Nginx
- Add a super basic Travis file

The diff is not as bad as it looks :p

### CODE REVIEW

**Comment by smn** [comment]
Thanks for setting this up, where will nginx log to if we're not specifing stderr & stdout? I had to add those so I could see logs in the container output.

**Comment by JayH5** [comment]
@smn Nginx should log everything to stdout/err by default due to this: https://github.com/praekeltfoundation/docker-junebug/blob/2a07d5ebe33e3753d95b9bea570a6ff9ed5f5669/Dockerfile#L10-L12

But.. on second thought.. I'm gonna test that this works...

**Comment by JayH5** [comment]
@smn: all logs from Nginx should now go to stdout/stderr by default.

**Comment by smn** [comment]
:+1:

**Pull request merged**
